name: Go Tests

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      env:
        JWT_SECRET: test_secret
        RATE_LIMIT_PER_MINUTE: 2
        ETHEREUM_RPC_URL: https://mock.ethereum.node
        POLYGON_RPC_URL: https://mock.polygon.node 
      run: go test -v ./...

    - name: Post Test Results
      if: ${{ failure() }}
      run: echo "Tests failed!" && exit 1
